mode: daemonset

image:
  repository: otel/opentelemetry-collector
  tag: 0.111.0
clusterRole:
  create: true
  rules:
  - apiGroups:
    - "*"
    resources:
    - "*"
    verbs:
    - "*"
config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
  extensions:
    health_check: {}
  processors:
    memory_limiter:
      check_interval: 1s
      limit_percentage: 75
      spike_limit_percentage: 15
    batch:
      send_batch_size: 10000
      timeout: 10
  exporters:
    otlp:
      endpoint: "http://tempo-distributor-discovery.monitoring:4317"
      tls:
        insecure: true
  service:
    extensions:
    - health_check
    pipelines:
      traces:
        exporters:
        - otlp
        processors:
        - memory_limiter
        - batch
        receivers:
        - otlp
ports:
  otlp:
    enabled: true
    containerPort: 4317
    servicePort: 4317
    hostPort: 4317
    protocol: TCP
    appProtocol: grpc
  otlp-http:
    enabled: true
    containerPort: 4318
    servicePort: 4318
    hostPort: 4318
    protocol: TCP