apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python
  namespace: argocd
spec:
  project: default
  source:
    path: k8s/chart/python
    repoURL: https://github.com/inerplat/fastcampus-devops-testcode-example.git
    targetRevision: HEAD
  destination:
    namespace: python
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

