apiVersion: v1
kind: Service
metadata:
  name: c
spec:
  selector:
    app: c
  ports:
  - protocol: TCP
    port: 80
    targetPort: 7002
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: c
  template:
    metadata:
      labels:
        app: c
    spec:
      containers:
      - name: c
        image: bhs9610/python:otel-automatic-c
        command: ["/bin/sh"]
        args:
        - "-c"
        - |
          OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://${HOST_IP}:4318/v1/traces opentelemetry-instrument python automatic.py
        ports:
        - containerPort: 7002
          name: http
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: PORT
          value: "7002"
        - name: OTEL_SERVICE_NAME
          value: "c"
        - name: OTEL_EXPORTER_OTLP_TRACES_HEADERS
          value: "api-key=key,other-config-value=value"
        - name: OTEL_TRACES_SAMPLER_ARG
          value: "100"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "http/protobuf"
        - name: OTEL_METRICS_EXPORTER
          value: "none"
        - name: OTEL_TRACES_EXPORTER
          value: "console,otlp"