apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: alb
spec:
  scaleTargetRef:
    name: nginx    
  minReplicaCount: 1  
  maxReplicaCount: 20  
  pollingInterval: 10   
  cooldownPeriod: 20
  triggers:
  - type: aws-cloudwatch
    metadata:
      namespace: AWS/ApplicationELB
      expression: SELECT COUNT(RequestCountPerTarget) FROM SCHEMA("AWS/ApplicationELB", LoadBalancer,TargetGroup)
      metricName: RequestCountPerTarget
      targetMetricValue: "60"
      minMetricValue: "0"
      awsRegion: "ap-northeast-2"
      identityOwner: operator 
      metricCollectionTime: "60" 
      metricStat: "Average" 
      metricStatPeriod: "30" 
      metricUnit: "Count"
