atlantisUrl: http://atlantis.juneman.click
orgAllowlist: github.com/changhyuni/*

github:
  user: changhyuni
#   token: github_token
#   secret: github_webhook_token

## 개인 실습때는 apply_requirements: [] 로 하시는걸 추천드립니다
## approved, mergeable는 approve가 되거나 merger가 되어야지만 apply를 실행할 수 있습니다.
repoConfig: |-                                     
  repos:                                         
  - id: /.*/
    apply_requirements: [approved, mergeable]
    import_requirements: [approved, mergeable]
    workflow: default
    allowed_overrides: [workflow, apply_requirements]
    allow_custom_workflows: true
  workflows:
    default:
      plan:
        steps: [init, plan]
      apply:
        steps: [apply]    

ingress:
  enabled: true
  ingressClassName: alb
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /healthz
    # https://www.runatlantis.io/docs/api-endpoints
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  host: atlantis.juneman.click

volumeClaim:
  enabled: true
  dataStorage: 20Gi
  storageClassName: ebs

vcsSecretName: "atlantis-vcs"
basicAuthSecretName: "atlantis-basic-auth"