apiVersion: v1
kind: Service
metadata:
  name: b
spec:
  selector:
    app: b
  ports:
  - protocol: TCP
    port: 80
    targetPort: 7001
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: b
  template:
    metadata:
      labels:
        app: b
    spec:
      containers:
      - name: b
        image: bhs9610/python:otel-programmatic-b
        command: ["/bin/sh"]
        args:
        - "-c"
        - |
          OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://${HOST_IP}:4318/v1/traces opentelemetry-instrument python programmatic.py
        ports:
        - containerPort: 7001
          name: http
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: PORT
          value: "7001"
        - name: C_HOST
          value: "c"
        - name: C_PORT
          value: "80"
        - name: OTEL_SERVICE_NAME
          value: "b"
        - name: OTEL_TRACES_SAMPLER_ARG
          value: "100"
        - name: OTEL_TRACES_EXPORTER
          value: "console,otlp"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "http/protobuf"
        - name: OTEL_METRICS_EXPORTER
          value: "none"