apiVersion: apps/v1
kind: Deployment
metadata:
  name: cacoabank-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cacoabank-deployment
  template:
    metadata:
      labels:
        app: cacoabank-deployment
    spec:
      containers:
      - name: cacoabank-container
        image: nginx:1.23.4-alpine3.17
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: cacoabank 
              key: DB_HOST
        - name: APP
          valueFrom:
            secretKeyRef:
              name: cacoabank 
              key: APP
        ports:
        - containerPort: 3000
